version: '3.8'

services:
  iptv-service:
    image: akiralereal/iptv:latest
    container_name: iptv-service
    restart: always
    ports:
      - "1905:1905"  # 左侧 1905 为宿主机端口，可自定义
    environment:
      - mport=1905
      # - mpass=YOUR_PASSWORD  # 如果需要给直播源后台加密码，取消本行注释并修改
    volumes:
      - ./iptv_data:/iptv/data  # 配置文件和缓存数据持久化
